/*
* ADCAVR238P.c
*
* Created: 27/03/2022 09:39:04 PM
*  Author: PC
*/

#include "ADCAVR328P.h"
#include "../../Helpers/Std_Types.h"
#include "../../Helpers/Utils.h"
#include "../../MCAL_Registers/MEM_MapAvr328P.h"

static void (*FuncInterruptPtr)(void);
ADC_CONFIG_t ADCOBJ;
void ADC_Init(ADC_CONFIG_t *ADCObject)
{
	ADCOBJ = * ADCObject;
	WRITE_BIT(ADCSRA,ADEN,HIGH);
	WRITE_BIT(ADCSRA,ADSC,HIGH);
	switch (ADCObject->ADC_VREF)
	{
		case AREF:
		WRITE_BIT(ADMUX,REFS1,LOW);
		WRITE_BIT(ADMUX,REFS0,LOW);
		break;
		
		case AVcc:
		WRITE_BIT(ADMUX,REFS1,LOW);
		WRITE_BIT(ADMUX,REFS0,HIGH);
		break;

		case INTERNAL1V1:
		WRITE_BIT(ADMUX,REFS1,HIGH);
		WRITE_BIT(ADMUX,REFS0,HIGH);
		break;
	}
	switch (ADCObject->ADC_PRESCALER)
	{
		case FACTOR_2:
		WRITE_BIT(ADCSRA,ADPS0,HIGH);
		WRITE_BIT(ADCSRA,ADPS1,LOW);
		WRITE_BIT(ADCSRA,ADPS2,LOW);
		break;
		
		case FACTOR_4:
		WRITE_BIT(ADCSRA,ADPS0,LOW);
		WRITE_BIT(ADCSRA,ADPS1,HIGH);
		WRITE_BIT(ADCSRA,ADPS2,LOW);
		break;
		
		case FACTOR_8:
		WRITE_BIT(ADCSRA,ADPS0,HIGH);
		WRITE_BIT(ADCSRA,ADPS1,HIGH);
		WRITE_BIT(ADCSRA,ADPS2,LOW);
		break;

		case FACTOR_16:
		WRITE_BIT(ADCSRA,ADPS0,LOW);
		WRITE_BIT(ADCSRA,ADPS1,LOW);
		WRITE_BIT(ADCSRA,ADPS2,HIGH);
		break;

		case FACTOR_32:
		WRITE_BIT(ADCSRA,ADPS0,HIGH);
		WRITE_BIT(ADCSRA,ADPS1,LOW);
		WRITE_BIT(ADCSRA,ADPS2,HIGH);
		break;

		case FACTOR_64:
		WRITE_BIT(ADCSRA,ADPS0,LOW);
		WRITE_BIT(ADCSRA,ADPS1,HIGH);
		WRITE_BIT(ADCSRA,ADPS2,HIGH);
		break;

		case FACTOR_128:
		WRITE_BIT(ADCSRA,ADPS0,HIGH);
		WRITE_BIT(ADCSRA,ADPS1,HIGH);
		WRITE_BIT(ADCSRA,ADPS2,HIGH);
		break;
	}

	switch (ADCObject->ADC_INPUT_CHANEL)
	{
		case ADC0:
		WRITE_BIT(DIDR0,ADC0D,HIGH);
		WRITE_BIT(ADMUX,MUX0,LOW);
		WRITE_BIT(ADMUX,MUX1,LOW);
		WRITE_BIT(ADMUX,MUX2,LOW);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;

		case ADC1:
		WRITE_BIT(ADMUX,MUX0,HIGH);
		WRITE_BIT(ADMUX,MUX1,LOW);
		WRITE_BIT(ADMUX,MUX2,LOW);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;

		case ADC2:
		WRITE_BIT(ADMUX,MUX0,LOW);
		WRITE_BIT(ADMUX,MUX1,HIGH);
		WRITE_BIT(ADMUX,MUX2,LOW);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;
		case ADC3:
		WRITE_BIT(ADMUX,MUX0,HIGH);
		WRITE_BIT(ADMUX,MUX1,HIGH);
		WRITE_BIT(ADMUX,MUX2,LOW);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;

		case ADC4:
		WRITE_BIT(ADMUX,MUX0,LOW);
		WRITE_BIT(ADMUX,MUX1,LOW);
		WRITE_BIT(ADMUX,MUX2,HIGH);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;
		case ADC5:
		WRITE_BIT(ADMUX,MUX0,LOW);
		WRITE_BIT(ADMUX,MUX1,HIGH);
		WRITE_BIT(ADMUX,MUX2,LOW);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;
	}

	switch (ADCObject->ADC_ATrigger_Selections)
	{
		case ADC_AT_DISABLE:
		WRITE_BIT(ADCSRA , ADATE , LOW);  // disable auto trigger		
		break;

		case FREE_RUNNIN_MODE:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,LOW);
		WRITE_BIT(ADCSRB,ADTS1,LOW);
		WRITE_BIT(ADCSRB,ADTS2,LOW);
		break;

		case ANALOG_COMPARATOR:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,HIGH);
		WRITE_BIT(ADCSRB,ADTS1,LOW);
		WRITE_BIT(ADCSRB,ADTS2,LOW);
		break;


		case EXTINT0:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,LOW);
		WRITE_BIT(ADCSRB,ADTS1,HIGH);
		WRITE_BIT(ADCSRB,ADTS2,LOW);
		break;

		case TIMER0COMPAREA:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,HIGH);
		WRITE_BIT(ADCSRB,ADTS1,HIGH);
		WRITE_BIT(ADCSRB,ADTS2,LOW);
		break;

		case TIMER0OVF:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,LOW);
		WRITE_BIT(ADCSRB,ADTS1,LOW);
		WRITE_BIT(ADCSRB,ADTS2,HIGH);
		break;
		
		case TIMER1COMPAREB:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,HIGH);
		WRITE_BIT(ADCSRB,ADTS1,LOW);
		WRITE_BIT(ADCSRB,ADTS2,HIGH);
		break;
		
		case TIMER1OVF:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,LOW);
		WRITE_BIT(ADCSRB,ADTS1,HIGH);
		WRITE_BIT(ADCSRB,ADTS2,HIGH);
		break;

		case TIMER1CAPTCHER:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,HIGH);
		WRITE_BIT(ADCSRB,ADTS1,HIGH);
		WRITE_BIT(ADCSRB,ADTS2,HIGH);
		break;
	}

	switch(ADCObject->ADC_ADLER)
	{
		case ADC_ADLER_RIGHT:
		WRITE_BIT(ADMUX,ADLAR,LOW);
		break;

		case ADC_ADLER_Left:
		WRITE_BIT(ADMUX,ADLAR,HIGH);
		break;
	}
	
	switch(ADCObject->ADC_INTERRUPT_Stats)
	{
		case EnableInterrupt:
		WRITE_BIT(ADCSRA,ADIE,HIGH);
		break;

		case DisableInterrupt:
		WRITE_BIT(ADCSRA,ADIE,LOW);
		break;
	}

}

uint16 ADC_READ(void)
{
	uint16 data=0;
	ADC_StarConvetion(); // start conversion
	while(GET_BIT(ADCSRA ,ADIF) == 0);  // wait until conversion completes , flag = 1when conversion completes
	data=((uint8)ADCL)|(ADCH<<8);
	return data;
}

void ADC_StarConvetion()
{
	WRITE_BIT(ADCSRA , ADSC , HIGH); // start conversion
}

void ADC_Enable()
{
	WRITE_BIT(ADCSRA , 7,HIGH);//enable adc module
}

void ADC_Disable()
{
	WRITE_BIT(ADCSRA , 7,LOW);//enable adc module
}

void ADC_ChangePrescaler(ADC_PRESCALER_t ADC_PRESCAL)
{
	ADCOBJ.ADC_PRESCALER = ADC_PRESCAL;
	switch (ADCOBJ.ADC_PRESCALER)
	{
		case FACTOR_2:
		WRITE_BIT(ADCSRA,ADPS0,HIGH);
		WRITE_BIT(ADCSRA,ADPS1,LOW);
		WRITE_BIT(ADCSRA,ADPS2,LOW);
		break;
		
		case FACTOR_4:
		WRITE_BIT(ADCSRA,ADPS0,LOW);
		WRITE_BIT(ADCSRA,ADPS1,HIGH);
		WRITE_BIT(ADCSRA,ADPS2,LOW);
		break;
		
		case FACTOR_8:
		WRITE_BIT(ADCSRA,ADPS0,HIGH);
		WRITE_BIT(ADCSRA,ADPS1,HIGH);
		WRITE_BIT(ADCSRA,ADPS2,LOW);
		break;

		case FACTOR_16:
		WRITE_BIT(ADCSRA,ADPS0,LOW);
		WRITE_BIT(ADCSRA,ADPS1,LOW);
		WRITE_BIT(ADCSRA,ADPS2,HIGH);
		break;

		case FACTOR_32:
		WRITE_BIT(ADCSRA,ADPS0,HIGH);
		WRITE_BIT(ADCSRA,ADPS1,LOW);
		WRITE_BIT(ADCSRA,ADPS2,HIGH);
		break;

		case FACTOR_64:
		WRITE_BIT(ADCSRA,ADPS0,LOW);
		WRITE_BIT(ADCSRA,ADPS1,HIGH);
		WRITE_BIT(ADCSRA,ADPS2,HIGH);
		break;

		case FACTOR_128:
		WRITE_BIT(ADCSRA,ADPS0,HIGH);
		WRITE_BIT(ADCSRA,ADPS1,HIGH);
		WRITE_BIT(ADCSRA,ADPS2,HIGH);
		break;
	}
}

void ADC_ChangeVREFRANCE(ADC_VREF_t ADC_VREFRANCE)
{
	ADCOBJ.ADC_VREF = ADC_VREFRANCE;
	switch (ADCOBJ.ADC_VREF)
	{
		case AREF:
		WRITE_BIT(ADMUX,REFS1,LOW);
		WRITE_BIT(ADMUX,REFS0,LOW);
		break;
		
		case AVcc:
		WRITE_BIT(ADMUX,REFS1,LOW);
		WRITE_BIT(ADMUX,REFS0,HIGH);
		break;

		case INTERNAL1V1:
		WRITE_BIT(ADMUX,REFS1,HIGH);
		WRITE_BIT(ADMUX,REFS0,HIGH);
		break;
	}
}

void ADC_ChangeADC_CHANEL(ADC_PRESCALER_t ADC_CHANEL)
{
	ADCOBJ.ADC_INPUT_CHANEL = ADC_CHANEL;
	switch (ADCOBJ.ADC_INPUT_CHANEL)
	{
		case ADC0:
		WRITE_BIT(ADMUX,MUX0,LOW);
		WRITE_BIT(ADMUX,MUX1,LOW);
		WRITE_BIT(ADMUX,MUX2,LOW);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;

		case ADC1:
		WRITE_BIT(ADMUX,MUX0,HIGH);
		WRITE_BIT(ADMUX,MUX1,LOW);
		WRITE_BIT(ADMUX,MUX2,LOW);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;

		case ADC2:
		WRITE_BIT(ADMUX,MUX0,LOW);
		WRITE_BIT(ADMUX,MUX1,HIGH);
		WRITE_BIT(ADMUX,MUX2,LOW);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;
		case ADC3:
		WRITE_BIT(ADMUX,MUX0,HIGH);
		WRITE_BIT(ADMUX,MUX1,HIGH);
		WRITE_BIT(ADMUX,MUX2,LOW);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;

		case ADC4:
		WRITE_BIT(ADMUX,MUX0,LOW);
		WRITE_BIT(ADMUX,MUX1,LOW);
		WRITE_BIT(ADMUX,MUX2,HIGH);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;
		case ADC5:
		WRITE_BIT(ADMUX,MUX0,LOW);
		WRITE_BIT(ADMUX,MUX1,HIGH);
		WRITE_BIT(ADMUX,MUX2,LOW);
		WRITE_BIT(ADMUX,MUX3,LOW);
		break;
	}
}

void ADC_ChangeATrigger(ADC_ATrigger_Selections_t ATrigger)
{
	ADCOBJ.ADC_ATrigger_Selections = ATrigger;
	switch (ADCOBJ.ADC_ATrigger_Selections)
	{
		case ADC_AT_DISABLE:
		WRITE_BIT(ADCSRA , ADATE , LOW);  // disable auto trigger
		
		break;

		case FREE_RUNNIN_MODE:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,LOW);
		WRITE_BIT(ADCSRB,ADTS1,LOW);
		WRITE_BIT(ADCSRB,ADTS2,LOW);
		break;

		case ANALOG_COMPARATOR:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,HIGH);
		WRITE_BIT(ADCSRB,ADTS1,LOW);
		WRITE_BIT(ADCSRB,ADTS2,LOW);
		break;


		case EXTINT0:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,LOW);
		WRITE_BIT(ADCSRB,ADTS1,HIGH);
		WRITE_BIT(ADCSRB,ADTS2,LOW);
		break;

		case TIMER0COMPAREA:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,HIGH);
		WRITE_BIT(ADCSRB,ADTS1,HIGH);
		WRITE_BIT(ADCSRB,ADTS2,LOW);
		break;

		case TIMER0OVF:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,LOW);
		WRITE_BIT(ADCSRB,ADTS1,LOW);
		WRITE_BIT(ADCSRB,ADTS2,HIGH);
		break;
		
		case TIMER1COMPAREB:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,HIGH);
		WRITE_BIT(ADCSRB,ADTS1,LOW);
		WRITE_BIT(ADCSRB,ADTS2,HIGH);
		break;
		
		case TIMER1OVF:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,LOW);
		WRITE_BIT(ADCSRB,ADTS1,HIGH);
		WRITE_BIT(ADCSRB,ADTS2,HIGH);
		break;

		case TIMER1CAPTCHER:
		WRITE_BIT(ADCSRA,ADATE,HIGH);
		WRITE_BIT(ADCSRB,ADTS0,HIGH);
		WRITE_BIT(ADCSRB,ADTS1,HIGH);
		WRITE_BIT(ADCSRB,ADTS2,HIGH);
		break;
	}
}

uint16 Get_ADCRegister()
{
	WRITE_BIT(ADCSRA , ADSC , HIGH); // start conversion
	return (((uint8)ADCL)|(ADCH<<8));
}

uint8 Get_ADCInterruptFlage()
{
	 return (GET_BIT(ADCSRA,ADIF));
}

void ADC_InitInterrupt(void(*ADC_InterruptFunctinPTR)(void))
{

}